# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: Aibat, phần mềm quản lý bán hàng
publish_to: none # Remove this line if you wish to publish to pub.dev
# To change version, use git tag command and push to remote (git push --tags)
# version: 99.99.99+99
version: 1.0.1+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  qr_flutter: ^4.0.0
  draggable_fab: ^0.1.4
  socket_io_client: ^3.0.0
  timelines: ^0.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  geolocator: ^10.0.0
  simple_gradient_text: ^1.3.0
  flutter_slidable: ^0.6.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4
  url_launcher: ^6.1.11
  google_fonts: ^5.0.0
  analyzer: ^5.7.1
  intl: ^0.18.0
  nylo_framework: 5.1.2
  pretty_dio_logger: ^1.3.1
  font_awesome_flutter: ^10.7.0
  multi_select_flutter: ^4.1.3
  image_picker: ^1.0.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  dropdown_search: ^5.0.6
  textfield_tags: ^2.0.2
  keyboard_actions: ^4.1.0
  currency_text_input_formatter: ^2.1.10
  flutter_typeahead: ^4.6.2
  audioplayers: ^5.0.0
  percent_indicator: ^4.0.1
  collection: ^1.16.0
  # ScreenUtil
  flutter_screenutil: ^5.5.4
  share_plus: ^7.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  global_configuration: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  mobile_scanner: ^3.3.0
  data_table_2: ^2.5.6
  printing: ^5.11.0
  upgrader: ^8.1.0
  flutter_contacts: ^1.1.8
  barcode_widget: ^2.0.0
  barcode: ^2.2.0
  barcode_image: ^2.0.0
  permission_handler: ^11.0.0
  after_layout: ^1.2.0
  infinite_scroll_pagination: ^4.0.0
  form_builder_file_picker: ^4.1.0
  image_cropper: ^5.0.0
  flutter_speed_dial: ^7.0.0
  input_quantity: ^2.1.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.7.0
  screenshot: ^2.1.0
  flutter_downloader: ^1.11.4
  device_info_plus: ^9.1.0
  photo_view: ^0.14.0
  #flutter_html_to_pdf:
  #  path: ./flutter_html_to_pdf
  #  flutter_inappwebview: ^5.8.0
  flutter_html: ^3.0.0-beta.2
  syncfusion_flutter_datepicker: ^23.1.44
  persistent_bottom_nav_bar_v2: ^4.2.8
  carousel_slider: ^4.2.1
  html_editor_enhanced: ^2.5.1
  file_picker: ^5.5.0
  http_parser: ^4.0.2
  pull_to_refresh: ^2.0.0
  otp_text_field: ^1.1.3
  flex_color_picker: ^3.3.0
  crypto: ^3.0.3
  flutter_svg: ^2.0.9
  thermal_printer: ^1.0.5
  flutter_bluetooth_printer: ^2.12.0
  esc_pos_utils_plus: ^2.0.3
  network_info_plus: ^4.1.0
  pusher_channels_flutter: ^2.2.1
  intro_slider: ^4.2.1
  dart_ping_ios: ^4.0.2
  flutter_local_notifications: ^17.2.1+2
  table_calendar: ^3.0.9
  syncfusion_flutter_calendar: ^23.2.7
  time_range_picker: ^2.3.0
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6
  in_app_purchase_storekit: ^0.3.18+1
  firebase_analytics: ^10.10.7
  firebase_messaging: ^14.7.13
  firebase_crashlytics: ^3.5.7
  firebase_core: ^2.32.0
  syncfusion_flutter_pdfviewer: ^23.1.39
  diacritic: ^0.1.3
  gal: 2.1.4
  sunmi_printer_plus: ^2.1.01
  flutter_html_to_pdf_updated: ^1.0.0
  uuid: ^3.0.5
#  flutter_html_to_pdf: ^0.7.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  #  lints: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  network_info_plus: ^4.1.0
  flutter_inappwebview: 6.0.0

# <--
# APP ICON - public/assets/app_icon/icon.png
# Build icons: "flutter pub run flutter_launcher_icons:main"
flutter_launcher_icons:
  android: true
  ios: AppIcon # Crucial step
  image_path: public/assets/app_icon/icon.png
  image_path_ios: public/assets/app_icon/icon_ios_new.png
  remove_alpha_ios: true
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/images/svg/
    - public/assets/images/intro/
    - public/assets/images/test/
    - public/assets/app_icon/
    - assets/sounds/
    - assets/cfg/
    - lang/
    - .env
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packagespub
