// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC30NhenvJpAuAbYsMSbtJl0JCGBhVmBsY',
    appId: '1:296289207113:android:83d6dacda12468b643d098',
    messagingSenderId: '296289207113',
    projectId: 'aibat-99db7',
    storageBucket: 'aibat-99db7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm70o8X-g8dyyolVbZxS1y60CCw_aW1T4',
    appId: '1:296289207113:ios:1ed59369e0672dd943d098',
    messagingSenderId: '296289207113',
    projectId: 'aibat-99db7',
    storageBucket: 'aibat-99db7.appspot.com',
    androidClientId:
        '296289207113-87etojb71qe6p3khj3211h2k55ba0bji.apps.googleusercontent.com',
    iosClientId:
        '296289207113-tuurfr54tc8uv6sge38vgnn29ulueub3.apps.googleusercontent.com',
    iosBundleId: 'com.aibat.app',
  );
}
